<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
    <!-- TemplateBeginEditable name="doctitle" -->
    <title>TDSIN: Sapphire</title>
    <!-- TemplateEndEditable -->
    <link href="SapphireCSS.css" rel="stylesheet" type="text/css"/>
</head>

<body class="SapphireCSS">
<table width="1024" align="center">
    <tr>
        <td>
            <DIV ID="sapphire-top">
                <IMG SRC="./images/sapphire_top.png" WIDTH=1024 HEIGHT=182 ALT="">
            </DIV>
            <DIV ID="sapphire">
                <IMG SRC="./images/sapphire.png" WIDTH=310 HEIGHT=39 ALT="">
            </DIV>
            <DIV ID="login">
                <A HREF="./TDSInLogin.php"><IMG SRC="./images/login.png" WIDTH=63 HEIGHT=39 ALT=""></A>
            </DIV>
            <DIV ID="home">
                <A HREF="./TDSInHome.php"><IMG SRC="./images/home.png" WIDTH=67 HEIGHT=39 ALT=""></A>
            </DIV>
            <DIV ID="mypage">
                <A HREF="./TDSInPlayerPage.php"><IMG SRC="./images/mypage.png" WIDTH=99 HEIGHT=39 ALT=""></A>
            </DIV>
            <DIV ID="viewops">
                <A HREF="./TDSINViewOp.php"><IMG SRC="./images/viewops.png" WIDTH=107 HEIGHT=39 ALT=""></A>
            </DIV>
            <DIV ID="admin">
                <A HREF="./TDSInAdminTools.php"><IMG SRC="./images/admin.png" WIDTH=82 HEIGHT=39 ALT=""></A>
            </DIV>
            <DIV ID="right">
                <IMG SRC="./images/right.png" WIDTH=296 HEIGHT=39 ALT="">
            </DIV>
            <DIV ID="bottom">
                <!-- TemplateBeginEditable name="content" -->
                <DIV ID="content_area">

                    Hey, Dean, put content generated by code here.

                </DIV>
                <!-- TemplateEndEditable -->
            </DIV>
        </td>
    </tr>
</table>
</body>
</html>
